### ISSUE TITLE
create a design doc for the application

### ISSUE THREAD

**Issue by ashutosh321607** [OpenLake/Knowlege-Sharing-Platform#1]
As this application is just an idea so we want to fix what are the functionalities that the app should have,
so I request you to give some interesting ideas and fix the design of the project.

with that, you can make your first contribution to this project,

**Comment by sahanmndl** [comment]
I have a suggestion, since this is a Knowledge sharing platform, so apart from the core functionalities like sharing study notes and professors/courses reviews, can't we add the QnA feature like Quora or Stackoverflow does. Students will ask their academic/institute related doubts which can be answered by their peers/seniors. In this way, numerous repetitive doubts will remain answered (and so every year freshers will get all their confusions cleared). All we need is to search our doubt :)

**Comment by Ananyaiitbhilai** [comment]
I have made a very basic work flow.
<img width="1504" alt="flow for knowledge sharing" src="https://user-images.githubusercontent.com/65886348/121004891-d4988600-c7ac-11eb-9170-f23dc775d407.png">


Frontend UI
1)Registration page having following fields
-username
-first name
-last name
-email
-Password
-timestamp at time of registering(database field)<automatic>
2)Information updating page
-Profile photo
-About
-college
-Other parameters
3)Dashboard of user/feedback page
(pls see that one in the file attached)

There can be further features like-upvoting, commenting on a particular feedback of course.
-follow/unfollow a user
-notifications when someone upvotes feedback, follows that user.
-search bar, so that a user can look for all the reviews of a particular course(keywords of a feedback can be extracted using rake algorithm)

The job before dashboard creation is easy but after that there is integration of multiple features like nested comments, notification, follow/unfollow, upvoting, etc. And many tables would be there.

The other feature is of resolving doubts, according to me for QnA, a different dashboard would be there, where user can answer the unanswered questions and it would also have the same features like-upvoting a particular ans/ques, commenting on a particular ans.

**Comment by Ananyaiitbhilai** [comment]
@ashutosh321607

**Comment by ashutosh321607** [comment]
@Ananyaiitbhilai  @sahanmndl  Thanks for your valuable feedbacks.
